DATA SEGMENT
ARRAY DW 1050H,2050H,3050H,5050H
LEN EQU (($-ARRAY)/2)
KEY DW 20H
STR1 DB 'KEY FOUND $'
STR2 DB 'KEY NOT FOUND $'
DATA ENDS

STACK SEGMENT
DW 128 DUP(?)
STACK ENDS

PRINT MACRO MSG
LEA DX,MSG
MOV AH,09H
INT 21H
ENDM

CODE SEGMENT
ASSUME CS:CODE,DS:DATA,SS:STACK

    START:
    MOV AX,DATA
    MOV DS,AX
    LEA SI,ARRAY
    MOV CX,LEN
    MOV BX,KEY
    FIND:
        MOV AX,[SI]
        CMP AX,BX
        JE FOUND
        ADD SI,2
        LOOP FIND
        PRINT STR2
        JMP STOP
    FOUND:
        PRINT STR1
        STOP:
        MOV AH,4CH
        INT 21H
CODE ENDS
END START