DATA SEGMENT   
N1 DW 0000H
N2 DW 0000H
N3 DW 0000H
N4 DW 0000H
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    MOV AX,N1
    MOV BX,N2
    MUL BX      ; Lower Bit in AX, Higher Bit in DX
    MOV N3,AX
    MOV N4,DX
    INT 3H
CODE ENDS
END START